# Generated by Django 4.2.11 on 2024-12-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0016_alter_band_cover_photo_alter_band_logo'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bands',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='bands.band'),
        ),
    ]
