# Generated by Django 4.2.11 on 2025-01-03 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bands',
        ),
    ]
