# Generated by Django 4.2.11 on 2024-12-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='provider',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
