# Generated by Django 4.2.7 on 2025-01-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.RemoveField(
            model_name='track',
            name='band',
        ),
        migrations.RemoveField(
            model_name='music',
            name='href',
        ),
        migrations.RemoveField(
            model_name='music',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='music',
            name='src',
        ),
        migrations.AddField(
            model_name='music',
            name='album_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='bandcamp_url',
            field=models.URLField(default='https://stilted.bandcamp.com/track/were-gonna-make-it'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='track_id',
            field=models.CharField(default=8675309, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(default=8675309, max_length=128),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
