# Generated by Django 4.2.7 on 2025-01-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_track_album_remove_track_band_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name_plural': 'music'},
        ),
        migrations.AlterField(
            model_name='music',
            name='track_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
