[mypy]
python_version = 3.11
ignore_missing_imports = True
check_untyped_defs = True
disallow_untyped_defs = True
warn_unused_ignores = True
warn_return_any = True
warn_unused_configs = True

# You can add per-module options below
# [mypy-some_module]
# disallow_untyped_defs = False
