# Generated by Django 4.2.7 on 2025-01-11 17:49

import bands.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_password', models.CharField(blank=True, max_length=128, null=True)),
                ('smtp_server', models.CharField(blank=True, max_length=128, null=True)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=bands.models.band_logo_path)),
                ('logo_alt', models.CharField(blank=True, help_text="Alt text for the band's logo", max_length=128)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to=bands.models.band_cover_path)),
                ('cover_photo_alt', models.CharField(blank=True, help_text="Alt text for the band's cover photo", max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
