# Generated by Django 4.2.11 on 2024-10-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='band_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='band_url',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='contact_email',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
