# Generated by Django 4.2.11 on 2024-11-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_alter_band_band_name_alter_band_band_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
