# Generated by Django 4.2.11 on 2024-11-24 17:54

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_band_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='email_password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=128, null=True)),
        ),
        migrations.AddField(
            model_name='band',
            name='logo',
            field=models.ImageField(null=True, upload_to='bands'),
        ),
        migrations.AddField(
            model_name='band',
            name='smtp_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='smtp_server',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
