# Generated by Django 4.2.11 on 2024-11-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_band_email_password_band_logo_band_smtp_port_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='band_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='band_url',
            new_name='url',
        ),
    ]
