# Generated by Django 4.2.11 on 2024-11-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_alter_band_cover_photo_alter_band_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='using_react',
            field=models.BooleanField(default=False),
        ),
    ]
