# Generated by Django 4.2.11 on 2024-12-24 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_content_type_image_object_id'),
        ('bands', '0014_band_logo_alter_band_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='cover_photo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_photos', to='images.image'),
        ),
    ]
