# Generated by Django 4.2.7 on 2025-01-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('street_address', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional information about the venue', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'city', 'state')},
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doors_at', models.DateTimeField(blank=True, help_text='When doors open', null=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='When the show starts', null=True)),
                ('ticket_price', models.CharField(blank=True, max_length=64)),
                ('presale_link', models.URLField(blank=True, null=True)),
                ('has_presale', models.BooleanField(default=False)),
                ('age_restriction', models.CharField(blank=True, max_length=32)),
                ('supporting_acts', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.band')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='shows.venue')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
    ]
