# Generated by Django 4.2.7 on 2025-01-11 18:35

from django.db import migrations, models
import shows.models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to=shows.models.show_flyer_path),
        ),
    ]
