# Generated by Django 4.2.3 on 2023-08-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='supporting_acts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
