# Generated by Django 4.2.3 on 2023-08-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_show_supporting_acts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.TimeField(null=True),
        ),
    ]
