# Generated by Django 4.2.3 on 2023-08-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_alter_show_show_date_alter_show_show_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='show_date',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_time',
        ),
        migrations.AddField(
            model_name='show',
            name='show_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
