# Generated by Django 4.2.3 on 2023-08-22 01:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_remove_show_show_date_remove_show_show_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.ImageField(null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/media/photos')),
        ),
    ]
