# Generated by Django 4.2.3 on 2023-08-22 01:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_show_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/media')),
        ),
    ]
