# Generated by Django 4.2.3 on 2023-08-22 01:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_alter_show_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/tmp'), upload_to=''),
        ),
    ]
