# Generated by Django 4.2.3 on 2024-01-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_alter_show_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='supporting_acts',
        ),
    ]
