# Generated by Django 4.2.3 on 2024-01-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_remove_show_supporting_acts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(null=True, upload_to='shows'),
        ),
    ]
