# Generated by Django 4.2.11 on 2024-10-01 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
        ('shows', '0011_alter_show_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='band',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bands.band'),
            preserve_default=False,
        ),
    ]
