# Generated by Django 4.2.11 on 2024-11-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0012_show_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shows'),
        ),
    ]
