# Generated by Django 4.2.11 on 2024-12-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0013_alter_show_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='image',
        ),
    ]
